"""add is_hidden to articles

Revision ID: 3e28f3bd74b7
Revises: 784a577dd6ae
Create Date: 2026-03-05 12:03:02.243911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e28f3bd74b7"
down_revision: Union[str, Sequence[str], None] = "784a577dd6ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column("articles", sa.Column("is_hidden", sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE articles SET is_hidden = false")
    # Make it non-nullable
    op.alter_column("articles", "is_hidden", nullable=False)

    op.create_index("ix_articles_is_hidden", "articles", ["is_hidden"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_articles_is_hidden", table_name="articles")
    op.create_index(
        op.f("ix_articles_embedding_hnsw"),
        "articles",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_column("articles", "is_hidden")
    # ### end Alembic commands ###
